export const FETCH_TASK = 'FETCH_TASK';
export const FETCH_TASK_SUCCESS = 'FETCH_TASK_SUCCESS';
export const FETCH_TASK_FAIL = 'FETCH_TASK_FAIL';
export const FILTER_TASK = 'FFILTER_TASK';
export const FILTER_TASK_SUCCESS = 'FFILTER_TASK_SUCCESS';
export const FILTER_TASK_FAIL = 'FILTER_TASK_FAIL';
